<div class="ultity-container">
    <strong class="text-title">Tiện Ích</strong>
    <div class="ultity">
        <div class="u_p_1 item">
            <div class="info">
                <div>DỰ BÁO THỜI TIẾT</div>
                <a href="/du-bao-thoi-tiet">Xem ngay</a>
            </div>
            <div class="overlay"></div>
        </div>
        <div class="u_p_2 item">
            <div class="info">
                <div>TỈ GIÁ TIỀN TỆ</div>
                <a href="/ti-gia-tien-te">Xem ngay</a>
            </div>
            <div class="overlay"></div>
        </div>

        <div class="u_p_3 item">
            <div class="info">
                <div>BẢN TIN KINH DOANH</div>
                <a href="/ban-tin-kinh-doanh">Xem ngay</a>
            </div>
            <div class="overlay"></div>
        </div>
    </div>
</div>

<style>
    @import url("https://fonts.googleapis.com/css2?family=Fira+Sans:wght@400&family=Playfair+Display&display=swap");

    *:not(.socials-block, .fa, .fab, .fas, .far) {
        font-family: "Fira Sans", sans-serif !important;
    }

    .block-title {
        text-align: center;
        word-spacing: 3px;
        color: #070404;
        text-shadow: 0px 1px 4px white;
        text-transform: uppercase;
    }

    .block-title strong {
        font-size: 22px !important;
    }

    .header {
        color: white;
    }

    .header .authorization-link {
        font-size: 14px !important;
    }

    .page-bottom {
        width: 100% !important;
    }

    .overlay {
        background-color: #000;
        width: 100%;
        height: 100%;
        position: absolute;
        opacity: 0.1;
        transition: 0.2s;
    }

    .info {
        margin-left: 5%;
        z-index: 10;
        color: white;
    }

    .info>div {
        text-shadow: -2px 3px 2px rgba(2, 2, 2, 0.5);
    }

    .ultity {
        width: 100%;
        display: flex;
        flex-wrap: wrap;
        font-size: 22px;
        font-weight: bold;
        padding-bottom: 40px;
    }

    .ultity>div {
        display: flex;
        position: relative;
        margin-right: 10px;
        margin-top: 10px;
        min-height: 200px;
        flex-grow: 1;
        min-width: 30%;
    }

    .ultity>div:hover .overlay {
        opacity: 0.5;
    }

    .ultity>div>div {
        font-size: 25px;
    }

    .ultity a {
        margin-top: 10px;
        color: #ffffff;
        text-decoration: none;
        display: inline-block;
        width: 140px;
        text-align: center;
        background: #000;
        border: 1.5px solid white;
        padding: 6px 3px;
        font-size: 22px !important;
        transition: 0.2s;
    }

    .ultity a:hover {
        background: #f66d1f;
    }

    .item {
        flex-direction: column;
        justify-content: center;
        background-size: cover;
    }

    .u_p_1 {
        background-image: url("https://i.imgur.com/DT5Eykx.png");
    }

    .u_p_2 {
        background-image: url("https://i.imgur.com/sPYL147.png");
    }

    .u_p_3 {
        background-image: url("http://bit.ueh.edu.vn/wp-content/uploads/2017/06/e-commerce.jpg");
    }

    .navigation {
        display: flex !important;
        align-items: center !important;
        background-color: #222 !important;
    }

    .navigation a {
        text-decoration: none;
        color: #222;
        transition: 0.2s;
    }

    .text-title {
        display: block;
        font-size: 22px;
        border-bottom: 2px solid #555;
        padding-bottom: 10px;
        line-height: 24px;
        color: #222222;
        letter-spacing: 0.5px;
        margin-bottom: 25px;
    }

    .ultity-container {
        max-width: 1280px;
        margin: auto;
    }

    .custom-p {
        display: flex;
        justify-content: flex-end;
    }
</style>