<table style="width:100%">
    <tr class="first-row">
        <th>TÊN NGOẠI TỆ</th>
        <th>MÃ NGOẠI TỆ</th>
        <th>TIỀN MẶT</th>
        <th>CHUYỂN KHOẢN</th>
        <th>BÁN</th>
    </tr>
    <?php
    $url = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=68";
    $feeds = simplexml_load_file($url);

    $i = 0;
    if (!empty($feeds)) {
        $extraList = $feeds->Exrate;
        foreach ($extraList as $item) {
            echo '
                <tr>
                    <th>' . $item['CurrencyName'] . '</th>
                    <th>' . $item['CurrencyCode'] . '</th>
                    <th>' . $item['Buy'] . '</th>
                    <th>' . $item['Transfer'] . '</th>
                    <th>' . $item['Sell'] . '</th>
                </tr>
            ';
        }
    }
    ?>
</table>

<style>
    .block-title {
        text-align: center;
        font-family: Oswald;
        word-spacing: 3px;
        letter-spacing: 4px;
        color: #070404;
        text-shadow: 0px 1px 4px white;
        text-transform: uppercase;
    }

    .block-title strong {
        font-size: 40px !important;
    }
</style>