<style>
    @import url("https://fonts.googleapis.com/css2?family=Fira+Sans:wght@400&family=Playfair+Display&display=swap");

    *:not(.socials-block, .fa, .fab, .fas, .far) {
        font-family: "Fira Sans", sans-serif !important;
    }

    .block-subtitle,
    .page-title-wrapper {
        line-height: 36px !important;
    }

    .page-title-wrapper {
        display: inline-block;
        padding-top: 10px;
    }

    @media only screen and (max-width: 768px) {
        .custom-p {
            width: 100%;
            display: flex;
            justify-content: flex-start;
        }

        #hb-testimonials {
            display: flex !important;
            flex-direction: column !important;
        }

        #hb-testimonials li {
            flex-grow: 1;
            width: auto !important;
        }
    }
</style>